config/routes.rb
CoinTrader::Application.routes.draw do

  resources :trades

  match 'root' => 'sessions#default', :via => :get
  match 'login' => 'sessions#new', :via => :get
  match 'logout' => 'sessions#destroy', :via => [:get, :delete]
  match 'signup' => 'users#new', :via => :get
  match '/'  => 'sessions#default', :via => :get
  match 'place_order'  => 'trades#new', :via => :get
  match 'index' => 'trades#index', :via => :get
  

  resource :session, :only => [:new, :create, :destroy]
  resource :account, :controller => 'users', :except => [:index, :destroy, :show, :edit]
end

app/models/trade.rb
class Trade < ActiveRecord::Base
	belongs_to :user
	attr_accessible :action_type, :valuation, :amount, :expiration, :suspended

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor	:password
	attr_protected	:password_digest

	validates	:email, :presence => true, :uniqueness => true, :email => true
	validates	:password, :presence => true, :confirmation => true
	validates	:password_confirmation, :presence => { :if => :password}
	has_many 	:trades
	
	def self.authenticate(email, pass)
		user = where(:email => email).first
		user && BCrypt::Password.new(user.password_digest) == pass ? user :nil
	end

	def password=(pass)
		return if pass.blank?
		@password=pass
		self.password_digest = BCrypt::Password.create(pass)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def require_user
  	return if current_user

  	respond_to do |format|
  		format.html {redirect_to login_path}
  		format.all {render :text => 'unauthorized', :status => :unauthorized}
  	end
  end


  def current_user
  	return @current_user if @current_user

  	if session[:user_id]
  		@current_user = User.find(session[:user_id])
  	elsif (header = request.headers['Aurhorization'].to_s.sub('Basic ', '')) != ''
  		header = Base64.decode64(header).split(':')
  		username = header.shift
  		@current_user = User.authenticate(username, password)
  	end
  end

  def create_user_session(user)
  	session[:user_id] = user.id
  end

  def destroy_user_session(user)
  	session[:user_id] = nil
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	respond_to :html, :json


	def create
		@user = User.authenticate(params[:email], params[:password])

		if @user
			create_user_session(@user)
			respond_with @user, :location => '/', :notice => 'Login Successful.'
		else
			respond_to do |format|
				format.html {render 'new'}
				format.json {render :json => {:error => 'Invalid email or password'}}
			end
		end
	end

	def destroy
		destroy_user_session
		redirect_to '/', :notice => 'Logged out.'
	end

end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  respond_to :json, :html

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all
    render json: @trades
  end


  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])
   
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    
    @trade = Trade.new(trade_params)

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render action: 'show', status: :ok, location: @trade }
      else
        format.html { render action: 'new' }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:action_type, :valuation, :amount, :expiration, :active, :executed, :suspended, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	respond_to :html, :json

	def new
		@user = User.new
	end

	def create
		@user = User.new(params[:user])
		if @user.save
			flash[:notice] = 'Your account has been created.'
		end
		respond_with @user, :location => '/default'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>BotCoinTrader</title>


 <%= javascript_include_tag "application" %>
 <%= stylesheet_link_tag "application" %>

<!--  <%= image_tag "application"  %> -->
 <%= csrf_meta_tags %>

</head>
<body>
	<div id='placemat'>
		<%= yield %>
	</div>
</body>
</html>

app/views/layouts/trades.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>BotCoinTrader</title>
 <%= javascript_include_tag "application" %>
 <%= stylesheet_link_tag "application" %>
 
<!--  <%= image_tag "application"  %> -->
 <%= csrf_meta_tags %>
</head>
<body>
	<div id='placemat'>
		<%= yield %>
	</div>
</body>
</html>

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :action_type %>
    <%= f.select :action_type, [['Buy', 'buy'], ['Sell', 'sell']] %>
  </div>
  <div class="field">
    <%= f.label :valuation %> <br>Execute when Bitcoins are worth:
    <%= f.text_field :valuation %>
  </div>
  <div class="field">
    <%= f.label :amount %> <br>I would like to trade this amount of Bitcoins or Dollars:
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :expiration %>
    <%= f.datetime_select :expiration %> GMT time
  </div>
  <!-- <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div> -->
  <!-- <div class="field">
    <%= f.label :executed %>
    <%= f.datetime_select :executed %>
  </div> -->
  <div class="field">
    <%= f.label :suspended %><br> Select to put trade on hold
    <%= f.check_box :suspended %>
  </div>
  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Valuation</th>
      <th>Amount</th>
      <th>Expiration</th>
      <th>Active</th>
      <th>Executed</th>
      <th>Suspended</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.action_type %></td>
        <td><%= trade.valuation %></td>
        <td><%= trade.amount %></td>
        <td><%= trade.expiration %></td>
        <td><%= trade.active %></td>
        <td><%= trade.executed %></td>
        <td><%= trade.suspended %></td>
        <td><%= trade.user_id %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New trade</h1>

<%= render 'form' %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @trade.action_type %>
</p>

<p>
  <strong>Valuation:</strong>
  <%= @trade.valuation %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @trade.amount %>
</p>

<p>
  <strong>Expiration:</strong>
  <%= @trade.expiration %>
</p>

<!-- <p>
  <strong>Active:</strong>
  <%= @trade.active %>
</p> -->

<!-- <p>
  <strong>Executed:</strong>
  <%= @trade.executed %>
</p> -->

<p>
  <strong>Suspended:</strong>
  <%= @trade.suspended %>
</p>

<!-- <p>
  <strong>User:</strong>
  <%= @trade.user_id %>
</p> -->

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag :users %>
<div id='signup-view'>
  <div class="page-header">
   <h1> Sign up for BotCoinTrader </h1>
 </div>
 
<%= form_tag account_path, :class => 'form-horizontal' do %>
    <div class="control-group">
    <%= label_tag :email, nil, :class => 'control-label' %>
      <div class="controls">
      <%= text_field_tag :email, nil, :placeholder => 'Dude@lebwoski.com' %>
     </div>
    </div>
 
    <div class="control-group">
      <%= label_tag :password, nil, :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password %>
      </div>
    </div>
 
    <div class="control-group">
      <%= label_tag :password_confirmation, 'Confirm', :class => 'control-label' %>
      <div class="controls">
        <%= password_field_tag :password_confirmation %>
      </div>
    </div>
 
    <div class="form-actions">
      <%= submit_tag "Signup", :class => 'btn btn-primary' %>
      <div class='clear'></div>
    </div>
 
  <% end %>
  <div class='clear'><div>
</div>